// Package proto implements the termhub wire protocol described in docs/M1-通信协议.md:
// frame formats for the three links, control messages, output offsets with
// gap recovery, bounded send queues, limits, error codes and version negotiation.
//
// It depends on nothing else in this module.
package proto

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

// Limits, docs/M1 第 10 节.
const (
	MaxFrame      = 1 << 20   // any binary frame
	MaxOutputData = 32 << 10  // data bytes in one output frame
	MaxInputData  = 64 << 10  // data bytes in one input frame
	MaxJSON       = 256 << 10 // one control message
	MaxChunk      = 1 << 20   // file transfer chunk
	MinCols       = 2
	MaxCols       = 500
	MinRows       = 1
	MaxRows       = 200
	SessionQueue  = 1 << 20 // per session / per attachment send queue
	InputQueue    = 8 << 20 // per session input queue: must hold one large paste
)

// Error codes, docs/M1 第 11 节.
const (
	ErrUnauthorized  = "unauthorized"
	ErrForbidden     = "forbidden"
	ErrNotFound      = "not_found"
	ErrNodeOffline   = "node_offline"
	ErrSessionExited = "session_exited"
	ErrUnsupported   = "unsupported"
	ErrProtoMismatch = "proto_mismatch"
	ErrFrameTooLarge = "frame_too_large"
	ErrInputOverflow = "input_overflow"
	ErrBadRequest    = "bad_request"
	ErrBusy          = "busy"
	ErrReadOnly      = "read_only"   // input from a viewer who does not drive the session
	ErrFolderBusy    = "folder_busy" // the same kind of CLI already runs in that folder
	ErrInternal      = "internal"
)

var (
	ErrFrameSize  = errors.New("proto: frame exceeds size limit")
	ErrFrameShort = errors.New("proto: frame too short")
	ErrFrameType  = errors.New("proto: unknown frame type")
	ErrBadSize    = errors.New("proto: terminal size out of range")
)

// SID is a session id: a UUIDv7, generated by the Hub, carried in full in
// every link B/C frame so no channel table has to survive a restart.
type SID [16]byte

// NewSID returns a UUIDv7 based on the current time.
func NewSID() SID {
	var s SID
	ms := uint64(time.Now().UnixMilli())
	binary.BigEndian.PutUint64(s[:8], ms<<16)
	if _, err := rand.Read(s[6:]); err != nil {
		panic("proto: no entropy: " + err.Error())
	}
	s[6] = 0x70 | s[6]&0x0f // version 7
	s[8] = 0x80 | s[8]&0x3f // variant
	return s
}

func (s SID) String() string {
	h := hex.EncodeToString(s[:])
	return h[:8] + "-" + h[8:12] + "-" + h[12:16] + "-" + h[16:20] + "-" + h[20:]
}

func (s SID) IsZero() bool { return s == SID{} }

// ParseSID accepts the canonical 36-character form.
func ParseSID(v string) (SID, error) {
	var s SID
	if len(v) != 36 || v[8] != '-' || v[13] != '-' || v[18] != '-' || v[23] != '-' {
		return s, fmt.Errorf("proto: bad session id %q", v)
	}
	b, err := hex.DecodeString(v[:8] + v[9:13] + v[14:18] + v[19:23] + v[24:])
	if err != nil {
		return s, fmt.Errorf("proto: bad session id %q", v)
	}
	copy(s[:], b)
	return s, nil
}

func (s SID) MarshalText() ([]byte, error) { return []byte(s.String()), nil }

func (s *SID) UnmarshalText(b []byte) error {
	v, err := ParseSID(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// CheckSize validates a terminal size against the protocol limits.
func CheckSize(cols, rows int) error {
	if cols < MinCols || cols > MaxCols || rows < MinRows || rows > MaxRows {
		return ErrBadSize
	}
	return nil
}
